version: '3.9'

services:
  family_budget_app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    restart: always

  postgres:
    ports:
      - "5432:5432"
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: assignment
      POSTGRES_DB: assignment
    volumes:
      - db-family_budget_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U assignment -d assignment
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  db-family_budget_data:
    name: family_budget_data
